-- MySQL Script generated by MySQL Workbench
-- Mon Jul 22 16:40:21 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema titulaciondb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema titulaciondb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `titulaciondb` DEFAULT CHARACTER SET utf8 ;
USE `titulaciondb` ;

-- -----------------------------------------------------
-- Table `titulaciondb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  `foto` VARCHAR(45) NULL,
  `ultimo_login` DATETIME NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`usuario_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`usuario_perfil` (
  `idusuario_perfil` INT NOT NULL AUTO_INCREMENT,
  `estado` TINYINT NULL,
  `idusuario` INT NOT NULL,
  `idperfil` INT NOT NULL,
  INDEX `usuario_perfil_usuario_idx` (`idusuario` ASC) VISIBLE,
  INDEX `usuario_perfil_perfil_idx` (`idperfil` ASC) VISIBLE,
  PRIMARY KEY (`idusuario_perfil`),
  CONSTRAINT `usuario_perfil_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `titulaciondb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario_perfil_perfil`
    FOREIGN KEY (`idperfil`)
    REFERENCES `titulaciondb`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`facultad` (
  `idfacultad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfacultad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`escuela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`escuela` (
  `idescuela` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `codigo` VARCHAR(27) NOT NULL,
  `idfacultad` INT NULL,
  INDEX `idfacultad_idx` (`idfacultad` ASC) VISIBLE,
  PRIMARY KEY (`idescuela`),
  CONSTRAINT `escuela_facultad`
    FOREIGN KEY (`idfacultad`)
    REFERENCES `titulaciondb`.`facultad` (`idfacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`bachiller`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`bachiller` (
  `idbachiller` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `codigo` VARCHAR(8) NULL,
  `dni` VARCHAR(8) NULL,
  `telefono` VARCHAR(8) NULL,
  `idusuario_perfil` INT NOT NULL,
  `idescuela` INT NOT NULL,
  PRIMARY KEY (`idbachiller`),
  INDEX `bachiller_usuario_perfil_idx` (`idusuario_perfil` ASC) VISIBLE,
  INDEX `bachiller_escuela_idx` (`idescuela` ASC) VISIBLE,
  CONSTRAINT `bachiller_usuario_perfil`
    FOREIGN KEY (`idusuario_perfil`)
    REFERENCES `titulaciondb`.`usuario_perfil` (`idusuario_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `bachiller_escuela`
    FOREIGN KEY (`idescuela`)
    REFERENCES `titulaciondb`.`escuela` (`idescuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`perfil_opcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`perfil_opcion` (
  `idperfil_opcion` INT NOT NULL AUTO_INCREMENT,
  `estado` TINYINT NULL,
  `idperfil` INT NOT NULL,
  `idopcion` INT NOT NULL,
  PRIMARY KEY (`idperfil_opcion`),
  INDEX `perfil_opcion_perfil_idx` (`idperfil` ASC) VISIBLE,
  INDEX `perfil_opcion_opcion_idx` (`idopcion` ASC) VISIBLE,
  CONSTRAINT `perfil_opcion_perfil`
    FOREIGN KEY (`idperfil`)
    REFERENCES `titulaciondb`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `perfil_opcion_opcion`
    FOREIGN KEY (`idopcion`)
    REFERENCES `titulaciondb`.`opcion` (`idopcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`decano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`decano` (
  `iddecano` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `telefono` VARCHAR(8) NULL,
  `dni` VARCHAR(8) NULL,
  `idusuario_perfil` INT NOT NULL,
  `idfacultad` INT NOT NULL,
  PRIMARY KEY (`iddecano`),
  INDEX `decano_facultad_idx` (`idfacultad` ASC) VISIBLE,
  INDEX `decano_usuario_perfil_idx` (`idusuario_perfil` ASC) VISIBLE,
  CONSTRAINT `decano_facultad`
    FOREIGN KEY (`idfacultad`)
    REFERENCES `titulaciondb`.`facultad` (`idfacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `decano_usuario_perfil`
    FOREIGN KEY (`idusuario_perfil`)
    REFERENCES `titulaciondb`.`usuario_perfil` (`idusuario_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`docente` (
  `iddocente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `idescuela` INT NOT NULL,
  `idusuario_perfil` INT NOT NULL,
  PRIMARY KEY (`iddocente`),
  INDEX `docente_escuela_idx` (`idescuela` ASC) VISIBLE,
  INDEX `docente_usuario_perfil_idx` (`idusuario_perfil` ASC) VISIBLE,
  CONSTRAINT `docente_escuela`
    FOREIGN KEY (`idescuela`)
    REFERENCES `titulaciondb`.`escuela` (`idescuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `docente_usuario_perfil`
    FOREIGN KEY (`idusuario_perfil`)
    REFERENCES `titulaciondb`.`usuario_perfil` (`idusuario_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`solicitud` (
  `idsolicitud` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idsolicitud`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`solucitud_asesoramiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`solucitud_asesoramiento` (
  `idsolucitud_asesoramiento` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(100) NULL,
  `estado` VARCHAR(45) NULL,
  `idsolicitud` INT NOT NULL,
  `idbachiller` INT NOT NULL,
  `iddocente` INT NOT NULL,
  PRIMARY KEY (`idsolucitud_asesoramiento`),
  INDEX `idsolicitud_idx` (`idsolicitud` ASC) VISIBLE,
  INDEX `solicitud_asesoramiento_docente_idx` (`iddocente` ASC) VISIBLE,
  INDEX `solicitud_asesoramiento_bachiller_idx` (`idbachiller` ASC) VISIBLE,
  CONSTRAINT `solicitud_asesoramiento_solicitud`
    FOREIGN KEY (`idsolicitud`)
    REFERENCES `titulaciondb`.`solicitud` (`idsolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `solicitud_asesoramiento_docente`
    FOREIGN KEY (`iddocente`)
    REFERENCES `titulaciondb`.`docente` (`iddocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `solicitud_asesoramiento_bachiller`
    FOREIGN KEY (`idbachiller`)
    REFERENCES `titulaciondb`.`bachiller` (`idbachiller`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`secretario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`secretario` (
  `idsecretario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `secretariocol` VARCHAR(45) NULL,
  `telefono` VARCHAR(9) NULL,
  `idescuela` INT NOT NULL,
  PRIMARY KEY (`idsecretario`),
  INDEX `secretario_escuela_idx` (`idescuela` ASC) VISIBLE,
  CONSTRAINT `secretario_escuela`
    FOREIGN KEY (`idescuela`)
    REFERENCES `titulaciondb`.`escuela` (`idescuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`solicitud_aprobacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`solicitud_aprobacion` (
  `idsolicitud_aprobacion` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(100) NULL,
  `estado` TINYINT NULL DEFAULT 0,
  `idsolicitud` INT NOT NULL,
  `idsolicitud_asesoramiento` INT NOT NULL,
  `idsecretario` INT NOT NULL,
  PRIMARY KEY (`idsolicitud_aprobacion`),
  INDEX `solicitud_aprobacion_solicitud_idx` (`idsolicitud` ASC) VISIBLE,
  INDEX `solicitud_aprobacion_asesoramiento_idx` (`idsolicitud_asesoramiento` ASC) VISIBLE,
  INDEX `solicitud_aprobacion_secretario_idx` (`idsecretario` ASC) VISIBLE,
  CONSTRAINT `solicitud_aprobacion_solicitud`
    FOREIGN KEY (`idsolicitud`)
    REFERENCES `titulaciondb`.`solicitud` (`idsolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `solicitud_aprobacion_asesoramiento`
    FOREIGN KEY (`idsolicitud_asesoramiento`)
    REFERENCES `titulaciondb`.`solucitud_asesoramiento` (`idsolucitud_asesoramiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `solicitud_aprobacion_secretario`
    FOREIGN KEY (`idsecretario`)
    REFERENCES `titulaciondb`.`secretario` (`idsecretario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`solicitud_plan_tesis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`solicitud_plan_tesis` (
  `idsolicitud_plan_tesis` INT NOT NULL AUTO_INCREMENT,
  `url_plan_tesis` VARCHAR(100) NULL,
  `pago_tramite` VARCHAR(45) NULL,
  `detalle` VARCHAR(100) NULL,
  `estado` VARCHAR(45) NULL,
  `idsolicitud_aprobacion` INT NOT NULL,
  PRIMARY KEY (`idsolicitud_plan_tesis`),
  INDEX `solicitud_plan_aprobacion_idx` (`idsolicitud_aprobacion` ASC) VISIBLE,
  CONSTRAINT `solicitud_plan_aprobacion`
    FOREIGN KEY (`idsolicitud_aprobacion`)
    REFERENCES `titulaciondb`.`solicitud_aprobacion` (`idsolicitud_aprobacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`comision`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`comision` (
  `idcomision` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(100) NULL,
  `estado` VARCHAR(45) NULL,
  `idsolicitud_plan_tesis` INT NOT NULL,
  PRIMARY KEY (`idcomision`),
  INDEX `comision_solicitud_plan_tesis_idx` (`idsolicitud_plan_tesis` ASC) VISIBLE,
  CONSTRAINT `comision_solicitud_plan_tesis`
    FOREIGN KEY (`idsolicitud_plan_tesis`)
    REFERENCES `titulaciondb`.`solicitud_plan_tesis` (`idsolicitud_plan_tesis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`comision_docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`comision_docente` (
  `idcomision_docente` INT NOT NULL AUTO_INCREMENT,
  `idcomision` INT NOT NULL,
  `iddocente` INT NOT NULL,
  PRIMARY KEY (`idcomision_docente`),
  INDEX `comision_docente_comision_idx` (`idcomision` ASC) VISIBLE,
  INDEX `comision_docente_docente_idx` (`iddocente` ASC) VISIBLE,
  CONSTRAINT `comision_docente_comision`
    FOREIGN KEY (`idcomision`)
    REFERENCES `titulaciondb`.`comision` (`idcomision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comision_docente_docente`
    FOREIGN KEY (`iddocente`)
    REFERENCES `titulaciondb`.`docente` (`iddocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`solicitud_borradora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`solicitud_borradora` (
  `idsolicitud_borradora` INT NOT NULL AUTO_INCREMENT,
  `pago_tramite` VARCHAR(45) NULL,
  `url_borradora` VARCHAR(100) NULL,
  `idcomision` INT NOT NULL,
  `idsecretario` INT NOT NULL,
  `iddecano` INT NOT NULL,
  PRIMARY KEY (`idsolicitud_borradora`),
  INDEX `solicitud_borradora_secretario_idx` (`idsecretario` ASC) VISIBLE,
  INDEX `solicitud_borradora_comision_idx` (`idcomision` ASC) VISIBLE,
  INDEX `solicitud_borradora_decano_idx` (`iddecano` ASC) VISIBLE,
  CONSTRAINT `solicitud_borradora_secretario`
    FOREIGN KEY (`idsecretario`)
    REFERENCES `titulaciondb`.`secretario` (`idsecretario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `solicitud_borradora_comision`
    FOREIGN KEY (`idcomision`)
    REFERENCES `titulaciondb`.`comision` (`idcomision`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `solicitud_borradora_decano`
    FOREIGN KEY (`iddecano`)
    REFERENCES `titulaciondb`.`decano` (`iddecano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`solicitud_sustentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`solicitud_sustentacion` (
  `idsolicitud_sustentacion` INT NOT NULL AUTO_INCREMENT,
  `solicitud_sustentacioncol` DATE NULL,
  `fecha` VARCHAR(45) NULL,
  `lugar` VARCHAR(100) NULL,
  `idsolicitud_borradora` INT NOT NULL,
  PRIMARY KEY (`idsolicitud_sustentacion`),
  INDEX `solicitud_sustentacion_borradora_idx` (`idsolicitud_borradora` ASC) VISIBLE,
  CONSTRAINT `solicitud_sustentacion_borradora`
    FOREIGN KEY (`idsolicitud_borradora`)
    REFERENCES `titulaciondb`.`solicitud_borradora` (`idsolicitud_borradora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`modulo` (
  `idmodulo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `icono` VARCHAR(20) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idmodulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`submodulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`submodulo` (
  `idsubmodulo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  `idmodulo` INT NOT NULL,
  PRIMARY KEY (`idsubmodulo`),
  INDEX `submodulo_modulo_idx` (`idmodulo` ASC) VISIBLE,
  CONSTRAINT `submodulo_modulo`
    FOREIGN KEY (`idmodulo`)
    REFERENCES `titulaciondb`.`modulo` (`idmodulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`opcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`opcion` (
  `idopcion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  `idsubmodulo` INT NOT NULL,
  PRIMARY KEY (`idopcion`),
  INDEX `opcion_submodulo_idx` (`idsubmodulo` ASC) VISIBLE,
  CONSTRAINT `opcion_submodulo`
    FOREIGN KEY (`idsubmodulo`)
    REFERENCES `titulaciondb`.`submodulo` (`idsubmodulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `titulaciondb`.`perfil_opcion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulaciondb`.`perfil_opcion` (
  `idperfil_opcion` INT NOT NULL AUTO_INCREMENT,
  `estado` TINYINT NULL,
  `idperfil` INT NOT NULL,
  `idopcion` INT NOT NULL,
  PRIMARY KEY (`idperfil_opcion`),
  INDEX `perfil_opcion_perfil_idx` (`idperfil` ASC) VISIBLE,
  INDEX `perfil_opcion_opcion_idx` (`idopcion` ASC) VISIBLE,
  CONSTRAINT `perfil_opcion_perfil`
    FOREIGN KEY (`idperfil`)
    REFERENCES `titulaciondb`.`perfil` (`idperfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `perfil_opcion_opcion`
    FOREIGN KEY (`idopcion`)
    REFERENCES `titulaciondb`.`opcion` (`idopcion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
