package pe.edu.unsch.entities;
// Generated 20/07/2019 08:17:53 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Bachiller generated by hbm2java
 */
public class Bachiller implements java.io.Serializable {

	private Integer idbachiller;
	private Escuela escuela;
	private UsuarioPerfil usuarioPerfil;
	private String nombre;
	private String apellido;
	private String codigo;
	private String dni;
	private String telefono;
	private Set solucitudAsesoramientos = new HashSet(0);

	public Bachiller() {
	}

	public Bachiller(Escuela escuela, UsuarioPerfil usuarioPerfil) {
		this.escuela = escuela;
		this.usuarioPerfil = usuarioPerfil;
	}

	public Bachiller(Escuela escuela, UsuarioPerfil usuarioPerfil, String nombre, String apellido, String codigo,
			String dni, String telefono, Set solucitudAsesoramientos) {
		this.escuela = escuela;
		this.usuarioPerfil = usuarioPerfil;
		this.nombre = nombre;
		this.apellido = apellido;
		this.codigo = codigo;
		this.dni = dni;
		this.telefono = telefono;
		this.solucitudAsesoramientos = solucitudAsesoramientos;
	}

	public Integer getIdbachiller() {
		return this.idbachiller;
	}

	public void setIdbachiller(Integer idbachiller) {
		this.idbachiller = idbachiller;
	}

	public Escuela getEscuela() {
		return this.escuela;
	}

	public void setEscuela(Escuela escuela) {
		this.escuela = escuela;
	}

	public UsuarioPerfil getUsuarioPerfil() {
		return this.usuarioPerfil;
	}

	public void setUsuarioPerfil(UsuarioPerfil usuarioPerfil) {
		this.usuarioPerfil = usuarioPerfil;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Set getSolucitudAsesoramientos() {
		return this.solucitudAsesoramientos;
	}

	public void setSolucitudAsesoramientos(Set solucitudAsesoramientos) {
		this.solucitudAsesoramientos = solucitudAsesoramientos;
	}

}
