package pe.edu.unsch.entities;
// Generated 21/07/2019 10:20:59 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ComisionDocente generated by hbm2java
 */
@Entity
@Table(name = "comision_docente", catalog = "titulaciondb")
public class ComisionDocente implements java.io.Serializable {

	private Integer idcomisionDocente;
	private Comision comision;
	private Docente docente;

	public ComisionDocente() {
	}

	public ComisionDocente(Comision comision, Docente docente) {
		this.comision = comision;
		this.docente = docente;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idcomision_docente", unique = true, nullable = false)
	public Integer getIdcomisionDocente() {
		return this.idcomisionDocente;
	}

	public void setIdcomisionDocente(Integer idcomisionDocente) {
		this.idcomisionDocente = idcomisionDocente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idcomision", nullable = false)
	public Comision getComision() {
		return this.comision;
	}

	public void setComision(Comision comision) {
		this.comision = comision;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iddocente", nullable = false)
	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

}
