package pe.edu.unsch.entities;
// Generated 20/07/2019 08:17:53 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Comision generated by hbm2java
 */
public class Comision implements java.io.Serializable {

	private Integer idcomision;
	private SolicitudPlanTesis solicitudPlanTesis;
	private String detalle;
	private String estado;
	private Set solicitudBorradoras = new HashSet(0);
	private Set comisionDocentes = new HashSet(0);

	public Comision() {
	}

	public Comision(SolicitudPlanTesis solicitudPlanTesis) {
		this.solicitudPlanTesis = solicitudPlanTesis;
	}

	public Comision(SolicitudPlanTesis solicitudPlanTesis, String detalle, String estado, Set solicitudBorradoras,
			Set comisionDocentes) {
		this.solicitudPlanTesis = solicitudPlanTesis;
		this.detalle = detalle;
		this.estado = estado;
		this.solicitudBorradoras = solicitudBorradoras;
		this.comisionDocentes = comisionDocentes;
	}

	public Integer getIdcomision() {
		return this.idcomision;
	}

	public void setIdcomision(Integer idcomision) {
		this.idcomision = idcomision;
	}

	public SolicitudPlanTesis getSolicitudPlanTesis() {
		return this.solicitudPlanTesis;
	}

	public void setSolicitudPlanTesis(SolicitudPlanTesis solicitudPlanTesis) {
		this.solicitudPlanTesis = solicitudPlanTesis;
	}

	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getSolicitudBorradoras() {
		return this.solicitudBorradoras;
	}

	public void setSolicitudBorradoras(Set solicitudBorradoras) {
		this.solicitudBorradoras = solicitudBorradoras;
	}

	public Set getComisionDocentes() {
		return this.comisionDocentes;
	}

	public void setComisionDocentes(Set comisionDocentes) {
		this.comisionDocentes = comisionDocentes;
	}

}
