package pe.edu.unsch.entities;
// Generated 20/07/2019 08:17:53 PM by Hibernate Tools 5.3.0.Beta2

/**
 * ComisionDocente generated by hbm2java
 */
public class ComisionDocente implements java.io.Serializable {

	private Integer idcomisionDocente;
	private Comision comision;
	private Docente docente;

	public ComisionDocente() {
	}

	public ComisionDocente(Comision comision, Docente docente) {
		this.comision = comision;
		this.docente = docente;
	}

	public Integer getIdcomisionDocente() {
		return this.idcomisionDocente;
	}

	public void setIdcomisionDocente(Integer idcomisionDocente) {
		this.idcomisionDocente = idcomisionDocente;
	}

	public Comision getComision() {
		return this.comision;
	}

	public void setComision(Comision comision) {
		this.comision = comision;
	}

	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

}
