package pe.edu.unsch.entities;
// Generated 08/07/2019 08:40:20 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Decano generated by hbm2java
 */
@Entity
@Table(name = "decano", catalog = "titulaciondb")
public class Decano implements java.io.Serializable {

	private int iddecano;
	private Facultad facultad;
	private UsuarioPerfil usuarioPerfil;
	private String nombre;
	private String apellido;
	private String telefono;
	private String dni;
	private Set<SolicitudBorradora> solicitudBorradoras = new HashSet<SolicitudBorradora>(0);

	public Decano() {
	}

	public Decano(int iddecano, Facultad facultad, UsuarioPerfil usuarioPerfil) {
		this.iddecano = iddecano;
		this.facultad = facultad;
		this.usuarioPerfil = usuarioPerfil;
	}

	public Decano(int iddecano, Facultad facultad, UsuarioPerfil usuarioPerfil, String nombre, String apellido,
			String telefono, String dni, Set<SolicitudBorradora> solicitudBorradoras) {
		this.iddecano = iddecano;
		this.facultad = facultad;
		this.usuarioPerfil = usuarioPerfil;
		this.nombre = nombre;
		this.apellido = apellido;
		this.telefono = telefono;
		this.dni = dni;
		this.solicitudBorradoras = solicitudBorradoras;
	}

	@Id

	@Column(name = "iddecano", unique = true, nullable = false)
	public int getIddecano() {
		return this.iddecano;
	}

	public void setIddecano(int iddecano) {
		this.iddecano = iddecano;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idfacultad", nullable = false)
	public Facultad getFacultad() {
		return this.facultad;
	}

	public void setFacultad(Facultad facultad) {
		this.facultad = facultad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario_perfil", nullable = false)
	public UsuarioPerfil getUsuarioPerfil() {
		return this.usuarioPerfil;
	}

	public void setUsuarioPerfil(UsuarioPerfil usuarioPerfil) {
		this.usuarioPerfil = usuarioPerfil;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", length = 45)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "telefono", length = 8)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "dni", length = 8)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "decano")
	public Set<SolicitudBorradora> getSolicitudBorradoras() {
		return this.solicitudBorradoras;
	}

	public void setSolicitudBorradoras(Set<SolicitudBorradora> solicitudBorradoras) {
		this.solicitudBorradoras = solicitudBorradoras;
	}

}
