package pe.edu.unsch.entities;
// Generated 20/07/2019 08:17:53 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente implements java.io.Serializable {

	private Integer iddocente;
	private Escuela escuela;
	private UsuarioPerfil usuarioPerfil;
	private String nombre;
	private String apellido;
	private String dni;
	private Set solucitudAsesoramientos = new HashSet(0);
	private Set comisionDocentes = new HashSet(0);

	public Docente() {
	}

	public Docente(Escuela escuela, UsuarioPerfil usuarioPerfil) {
		this.escuela = escuela;
		this.usuarioPerfil = usuarioPerfil;
	}

	public Docente(Escuela escuela, UsuarioPerfil usuarioPerfil, String nombre, String apellido, String dni,
			Set solucitudAsesoramientos, Set comisionDocentes) {
		this.escuela = escuela;
		this.usuarioPerfil = usuarioPerfil;
		this.nombre = nombre;
		this.apellido = apellido;
		this.dni = dni;
		this.solucitudAsesoramientos = solucitudAsesoramientos;
		this.comisionDocentes = comisionDocentes;
	}

	public Integer getIddocente() {
		return this.iddocente;
	}

	public void setIddocente(Integer iddocente) {
		this.iddocente = iddocente;
	}

	public Escuela getEscuela() {
		return this.escuela;
	}

	public void setEscuela(Escuela escuela) {
		this.escuela = escuela;
	}

	public UsuarioPerfil getUsuarioPerfil() {
		return this.usuarioPerfil;
	}

	public void setUsuarioPerfil(UsuarioPerfil usuarioPerfil) {
		this.usuarioPerfil = usuarioPerfil;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public Set getSolucitudAsesoramientos() {
		return this.solucitudAsesoramientos;
	}

	public void setSolucitudAsesoramientos(Set solucitudAsesoramientos) {
		this.solucitudAsesoramientos = solucitudAsesoramientos;
	}

	public Set getComisionDocentes() {
		return this.comisionDocentes;
	}

	public void setComisionDocentes(Set comisionDocentes) {
		this.comisionDocentes = comisionDocentes;
	}

}
