package pe.edu.unsch.entities;
// Generated 21/07/2019 10:20:59 AM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Docente generated by hbm2java
 */
@Entity
@Table(name = "docente", catalog = "titulaciondb")
public class Docente implements java.io.Serializable {

	private Integer iddocente;
	private Escuela escuela;
	private UsuarioPerfil usuarioPerfil;
	private String nombre;
	private String apellido;
	private String dni;
	private Set<SolucitudAsesoramiento> solucitudAsesoramientos = new HashSet<SolucitudAsesoramiento>(0);
	private Set<ComisionDocente> comisionDocentes = new HashSet<ComisionDocente>(0);

	public Docente() {
	}

	public Docente(Escuela escuela, UsuarioPerfil usuarioPerfil) {
		this.escuela = escuela;
		this.usuarioPerfil = usuarioPerfil;
	}

	public Docente(Escuela escuela, UsuarioPerfil usuarioPerfil, String nombre, String apellido, String dni,
			Set<SolucitudAsesoramiento> solucitudAsesoramientos, Set<ComisionDocente> comisionDocentes) {
		this.escuela = escuela;
		this.usuarioPerfil = usuarioPerfil;
		this.nombre = nombre;
		this.apellido = apellido;
		this.dni = dni;
		this.solucitudAsesoramientos = solucitudAsesoramientos;
		this.comisionDocentes = comisionDocentes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "iddocente", unique = true, nullable = false)
	public Integer getIddocente() {
		return this.iddocente;
	}

	public void setIddocente(Integer iddocente) {
		this.iddocente = iddocente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idescuela", nullable = false)
	public Escuela getEscuela() {
		return this.escuela;
	}

	public void setEscuela(Escuela escuela) {
		this.escuela = escuela;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario_perfil", nullable = false)
	public UsuarioPerfil getUsuarioPerfil() {
		return this.usuarioPerfil;
	}

	public void setUsuarioPerfil(UsuarioPerfil usuarioPerfil) {
		this.usuarioPerfil = usuarioPerfil;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellido", length = 45)
	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	@Column(name = "dni", length = 45)
	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
	public Set<SolucitudAsesoramiento> getSolucitudAsesoramientos() {
		return this.solucitudAsesoramientos;
	}

	public void setSolucitudAsesoramientos(Set<SolucitudAsesoramiento> solucitudAsesoramientos) {
		this.solucitudAsesoramientos = solucitudAsesoramientos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "docente")
	public Set<ComisionDocente> getComisionDocentes() {
		return this.comisionDocentes;
	}

	public void setComisionDocentes(Set<ComisionDocente> comisionDocentes) {
		this.comisionDocentes = comisionDocentes;
	}

}
