package pe.edu.unsch.entities;
// Generated 20/07/2019 08:17:53 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Escuela generated by hbm2java
 */
public class Escuela implements java.io.Serializable {

	private Integer idescuela;
	private Facultad facultad;
	private String nombre;
	private String codigo;
	private Set docentes = new HashSet(0);
	private Set bachillers = new HashSet(0);
	private Set secretarios = new HashSet(0);

	public Escuela() {
	}

	public Escuela(String nombre, String codigo) {
		this.nombre = nombre;
		this.codigo = codigo;
	}

	public Escuela(Facultad facultad, String nombre, String codigo, Set docentes, Set bachillers, Set secretarios) {
		this.facultad = facultad;
		this.nombre = nombre;
		this.codigo = codigo;
		this.docentes = docentes;
		this.bachillers = bachillers;
		this.secretarios = secretarios;
	}

	public Integer getIdescuela() {
		return this.idescuela;
	}

	public void setIdescuela(Integer idescuela) {
		this.idescuela = idescuela;
	}

	public Facultad getFacultad() {
		return this.facultad;
	}

	public void setFacultad(Facultad facultad) {
		this.facultad = facultad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Set getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Set docentes) {
		this.docentes = docentes;
	}

	public Set getBachillers() {
		return this.bachillers;
	}

	public void setBachillers(Set bachillers) {
		this.bachillers = bachillers;
	}

	public Set getSecretarios() {
		return this.secretarios;
	}

	public void setSecretarios(Set secretarios) {
		this.secretarios = secretarios;
	}

}
