package pe.edu.unsch.entities;
// Generated 20/07/2019 08:17:53 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Facultad generated by hbm2java
 */
public class Facultad implements java.io.Serializable {

	private Integer idfacultad;
	private String nombre;
	private Set escuelas = new HashSet(0);
	private Set decanos = new HashSet(0);

	public Facultad() {
	}

	public Facultad(String nombre) {
		this.nombre = nombre;
	}

	public Facultad(String nombre, Set escuelas, Set decanos) {
		this.nombre = nombre;
		this.escuelas = escuelas;
		this.decanos = decanos;
	}

	public Integer getIdfacultad() {
		return this.idfacultad;
	}

	public void setIdfacultad(Integer idfacultad) {
		this.idfacultad = idfacultad;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getEscuelas() {
		return this.escuelas;
	}

	public void setEscuelas(Set escuelas) {
		this.escuelas = escuelas;
	}

	public Set getDecanos() {
		return this.decanos;
	}

	public void setDecanos(Set decanos) {
		this.decanos = decanos;
	}

}
