package pe.edu.unsch.entities;
// Generated 08/07/2019 12:10:03 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PerfilOpcion generated by hbm2java
 */
@Entity
@Table(name = "perfil_opcion", catalog = "titulaciondb")
public class PerfilOpcion implements java.io.Serializable {

	private int idperfilOpcion;
	private Perfil perfil;
	private byte estado;

	public PerfilOpcion() {
	}

	public PerfilOpcion(int idperfilOpcion, Perfil perfil, byte estado) {
		this.idperfilOpcion = idperfilOpcion;
		this.perfil = perfil;
		this.estado = estado;
	}

	@Id

	@Column(name = "idperfil_opcion", unique = true, nullable = false)
	public int getIdperfilOpcion() {
		return this.idperfilOpcion;
	}

	public void setIdperfilOpcion(int idperfilOpcion) {
		this.idperfilOpcion = idperfilOpcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idperfil", nullable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@Column(name = "estado", nullable = false)
	public byte getEstado() {
		return this.estado;
	}

	public void setEstado(byte estado) {
		this.estado = estado;
	}

}
