package pe.edu.unsch.entities;
// Generated 08/07/2019 08:40:20 PM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PerfilOpcion generated by hbm2java
 */
@Entity
@Table(name = "perfil_opcion", catalog = "titulaciondb")
public class PerfilOpcion implements java.io.Serializable {

	private Integer idperfilOpcion;
	private Opcion opcion;
	private Perfil perfil;
	private Byte estado;

	public PerfilOpcion() {
	}

	public PerfilOpcion(Opcion opcion, Perfil perfil) {
		this.opcion = opcion;
		this.perfil = perfil;
	}

	public PerfilOpcion(Opcion opcion, Perfil perfil, Byte estado) {
		this.opcion = opcion;
		this.perfil = perfil;
		this.estado = estado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idperfil_opcion", unique = true, nullable = false)
	public Integer getIdperfilOpcion() {
		return this.idperfilOpcion;
	}

	public void setIdperfilOpcion(Integer idperfilOpcion) {
		this.idperfilOpcion = idperfilOpcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idopcion", nullable = false)
	public Opcion getOpcion() {
		return this.opcion;
	}

	public void setOpcion(Opcion opcion) {
		this.opcion = opcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idperfil", nullable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@Column(name = "estado")
	public Byte getEstado() {
		return this.estado;
	}

	public void setEstado(Byte estado) {
		this.estado = estado;
	}

}
