package pe.edu.unsch.entities;
// Generated 08/07/2019 08:40:20 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", catalog = "titulaciondb")
public class Perfil implements java.io.Serializable {

	private Integer idperfil;
	private String nombre;
	private Set<PerfilOpcion> perfilOpcions = new HashSet<PerfilOpcion>(0);
	private Set<UsuarioPerfil> usuarioPerfils = new HashSet<UsuarioPerfil>(0);

	public Perfil() {
	}

	public Perfil(String nombre) {
		this.nombre = nombre;
	}

	public Perfil(String nombre, Set<PerfilOpcion> perfilOpcions, Set<UsuarioPerfil> usuarioPerfils) {
		this.nombre = nombre;
		this.perfilOpcions = perfilOpcions;
		this.usuarioPerfils = usuarioPerfils;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idperfil", unique = true, nullable = false)
	public Integer getIdperfil() {
		return this.idperfil;
	}

	public void setIdperfil(Integer idperfil) {
		this.idperfil = idperfil;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<PerfilOpcion> getPerfilOpcions() {
		return this.perfilOpcions;
	}

	public void setPerfilOpcions(Set<PerfilOpcion> perfilOpcions) {
		this.perfilOpcions = perfilOpcions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<UsuarioPerfil> getUsuarioPerfils() {
		return this.usuarioPerfils;
	}

	public void setUsuarioPerfils(Set<UsuarioPerfil> usuarioPerfils) {
		this.usuarioPerfils = usuarioPerfils;
	}

}
