package pe.edu.unsch.entities;
// Generated 20/07/2019 08:17:53 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Secretario generated by hbm2java
 */
public class Secretario implements java.io.Serializable {

	private Integer idsecretario;
	private Escuela escuela;
	private String nombre;
	private String apellido;
	private String secretariocol;
	private String telefono;
	private Set solicitudAprobacions = new HashSet(0);
	private Set solicitudBorradoras = new HashSet(0);

	public Secretario() {
	}

	public Secretario(Escuela escuela) {
		this.escuela = escuela;
	}

	public Secretario(Escuela escuela, String nombre, String apellido, String secretariocol, String telefono,
			Set solicitudAprobacions, Set solicitudBorradoras) {
		this.escuela = escuela;
		this.nombre = nombre;
		this.apellido = apellido;
		this.secretariocol = secretariocol;
		this.telefono = telefono;
		this.solicitudAprobacions = solicitudAprobacions;
		this.solicitudBorradoras = solicitudBorradoras;
	}

	public Integer getIdsecretario() {
		return this.idsecretario;
	}

	public void setIdsecretario(Integer idsecretario) {
		this.idsecretario = idsecretario;
	}

	public Escuela getEscuela() {
		return this.escuela;
	}

	public void setEscuela(Escuela escuela) {
		this.escuela = escuela;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido() {
		return this.apellido;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public String getSecretariocol() {
		return this.secretariocol;
	}

	public void setSecretariocol(String secretariocol) {
		this.secretariocol = secretariocol;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public Set getSolicitudAprobacions() {
		return this.solicitudAprobacions;
	}

	public void setSolicitudAprobacions(Set solicitudAprobacions) {
		this.solicitudAprobacions = solicitudAprobacions;
	}

	public Set getSolicitudBorradoras() {
		return this.solicitudBorradoras;
	}

	public void setSolicitudBorradoras(Set solicitudBorradoras) {
		this.solicitudBorradoras = solicitudBorradoras;
	}

}
