package pe.edu.unsch.entities;
// Generated 20/07/2019 08:17:53 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * SolicitudBorradora generated by hbm2java
 */
public class SolicitudBorradora implements java.io.Serializable {

	private Integer idsolicitudBorradora;
	private Comision comision;
	private Decano decano;
	private Secretario secretario;
	private String pagoTramite;
	private String urlBorradora;
	private Set solicitudSustentacions = new HashSet(0);

	public SolicitudBorradora() {
	}

	public SolicitudBorradora(Comision comision, Decano decano, Secretario secretario) {
		this.comision = comision;
		this.decano = decano;
		this.secretario = secretario;
	}

	public SolicitudBorradora(Comision comision, Decano decano, Secretario secretario, String pagoTramite,
			String urlBorradora, Set solicitudSustentacions) {
		this.comision = comision;
		this.decano = decano;
		this.secretario = secretario;
		this.pagoTramite = pagoTramite;
		this.urlBorradora = urlBorradora;
		this.solicitudSustentacions = solicitudSustentacions;
	}

	public Integer getIdsolicitudBorradora() {
		return this.idsolicitudBorradora;
	}

	public void setIdsolicitudBorradora(Integer idsolicitudBorradora) {
		this.idsolicitudBorradora = idsolicitudBorradora;
	}

	public Comision getComision() {
		return this.comision;
	}

	public void setComision(Comision comision) {
		this.comision = comision;
	}

	public Decano getDecano() {
		return this.decano;
	}

	public void setDecano(Decano decano) {
		this.decano = decano;
	}

	public Secretario getSecretario() {
		return this.secretario;
	}

	public void setSecretario(Secretario secretario) {
		this.secretario = secretario;
	}

	public String getPagoTramite() {
		return this.pagoTramite;
	}

	public void setPagoTramite(String pagoTramite) {
		this.pagoTramite = pagoTramite;
	}

	public String getUrlBorradora() {
		return this.urlBorradora;
	}

	public void setUrlBorradora(String urlBorradora) {
		this.urlBorradora = urlBorradora;
	}

	public Set getSolicitudSustentacions() {
		return this.solicitudSustentacions;
	}

	public void setSolicitudSustentacions(Set solicitudSustentacions) {
		this.solicitudSustentacions = solicitudSustentacions;
	}

}
