package pe.edu.unsch.entities;
// Generated 20/07/2019 08:17:53 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Solicitud generated by hbm2java
 */
public class Solicitud implements java.io.Serializable {

	private Integer idsolicitud;
	private String nombre;
	private Set solicitudAprobacions = new HashSet(0);
	private Set solucitudAsesoramientos = new HashSet(0);

	public Solicitud() {
	}

	public Solicitud(String nombre, Set solicitudAprobacions, Set solucitudAsesoramientos) {
		this.nombre = nombre;
		this.solicitudAprobacions = solicitudAprobacions;
		this.solucitudAsesoramientos = solucitudAsesoramientos;
	}

	public Integer getIdsolicitud() {
		return this.idsolicitud;
	}

	public void setIdsolicitud(Integer idsolicitud) {
		this.idsolicitud = idsolicitud;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getSolicitudAprobacions() {
		return this.solicitudAprobacions;
	}

	public void setSolicitudAprobacions(Set solicitudAprobacions) {
		this.solicitudAprobacions = solicitudAprobacions;
	}

	public Set getSolucitudAsesoramientos() {
		return this.solucitudAsesoramientos;
	}

	public void setSolucitudAsesoramientos(Set solucitudAsesoramientos) {
		this.solucitudAsesoramientos = solucitudAsesoramientos;
	}

}
