package pe.edu.unsch.entities;
// Generated 08/07/2019 12:10:03 AM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SolicitudAprobacion generated by hbm2java
 */
@Entity
@Table(name = "solicitud_aprobacion", catalog = "titulaciondb")
public class SolicitudAprobacion implements java.io.Serializable {

	private int idsolicitudAprobacion;
	private Secretario secretario;
	private Solicitud solicitud;
	private SolucitudAsesoramiento solucitudAsesoramiento;
	private String detalle;
	private Byte estado;
	private Set<SolicitudPlanTesis> solicitudPlanTesises = new HashSet<SolicitudPlanTesis>(0);

	public SolicitudAprobacion() {
	}

	public SolicitudAprobacion(int idsolicitudAprobacion, Secretario secretario, Solicitud solicitud,
			SolucitudAsesoramiento solucitudAsesoramiento) {
		this.idsolicitudAprobacion = idsolicitudAprobacion;
		this.secretario = secretario;
		this.solicitud = solicitud;
		this.solucitudAsesoramiento = solucitudAsesoramiento;
	}

	public SolicitudAprobacion(int idsolicitudAprobacion, Secretario secretario, Solicitud solicitud,
			SolucitudAsesoramiento solucitudAsesoramiento, String detalle, Byte estado,
			Set<SolicitudPlanTesis> solicitudPlanTesises) {
		this.idsolicitudAprobacion = idsolicitudAprobacion;
		this.secretario = secretario;
		this.solicitud = solicitud;
		this.solucitudAsesoramiento = solucitudAsesoramiento;
		this.detalle = detalle;
		this.estado = estado;
		this.solicitudPlanTesises = solicitudPlanTesises;
	}

	@Id

	@Column(name = "idsolicitud_aprobacion", unique = true, nullable = false)
	public int getIdsolicitudAprobacion() {
		return this.idsolicitudAprobacion;
	}

	public void setIdsolicitudAprobacion(int idsolicitudAprobacion) {
		this.idsolicitudAprobacion = idsolicitudAprobacion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsecretario", nullable = false)
	public Secretario getSecretario() {
		return this.secretario;
	}

	public void setSecretario(Secretario secretario) {
		this.secretario = secretario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsolicitud", nullable = false)
	public Solicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(Solicitud solicitud) {
		this.solicitud = solicitud;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsolicitud_asesoramiento", nullable = false)
	public SolucitudAsesoramiento getSolucitudAsesoramiento() {
		return this.solucitudAsesoramiento;
	}

	public void setSolucitudAsesoramiento(SolucitudAsesoramiento solucitudAsesoramiento) {
		this.solucitudAsesoramiento = solucitudAsesoramiento;
	}

	@Column(name = "detalle", length = 100)
	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	@Column(name = "estado")
	public Byte getEstado() {
		return this.estado;
	}

	public void setEstado(Byte estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitudAprobacion")
	public Set<SolicitudPlanTesis> getSolicitudPlanTesises() {
		return this.solicitudPlanTesises;
	}

	public void setSolicitudPlanTesises(Set<SolicitudPlanTesis> solicitudPlanTesises) {
		this.solicitudPlanTesises = solicitudPlanTesises;
	}

}
