package pe.edu.unsch.entities;
// Generated 20/07/2019 08:17:53 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * SolicitudAprobacion generated by hbm2java
 */
public class SolicitudAprobacion implements java.io.Serializable {

	private Integer idsolicitudAprobacion;
	private Secretario secretario;
	private Solicitud solicitud;
	private SolucitudAsesoramiento solucitudAsesoramiento;
	private String detalle;
	private Byte estado;
	private Set solicitudPlanTesises = new HashSet(0);

	public SolicitudAprobacion() {
	}

	public SolicitudAprobacion(Secretario secretario, Solicitud solicitud,
			SolucitudAsesoramiento solucitudAsesoramiento) {
		this.secretario = secretario;
		this.solicitud = solicitud;
		this.solucitudAsesoramiento = solucitudAsesoramiento;
	}

	public SolicitudAprobacion(Secretario secretario, Solicitud solicitud,
			SolucitudAsesoramiento solucitudAsesoramiento, String detalle, Byte estado, Set solicitudPlanTesises) {
		this.secretario = secretario;
		this.solicitud = solicitud;
		this.solucitudAsesoramiento = solucitudAsesoramiento;
		this.detalle = detalle;
		this.estado = estado;
		this.solicitudPlanTesises = solicitudPlanTesises;
	}

	public Integer getIdsolicitudAprobacion() {
		return this.idsolicitudAprobacion;
	}

	public void setIdsolicitudAprobacion(Integer idsolicitudAprobacion) {
		this.idsolicitudAprobacion = idsolicitudAprobacion;
	}

	public Secretario getSecretario() {
		return this.secretario;
	}

	public void setSecretario(Secretario secretario) {
		this.secretario = secretario;
	}

	public Solicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(Solicitud solicitud) {
		this.solicitud = solicitud;
	}

	public SolucitudAsesoramiento getSolucitudAsesoramiento() {
		return this.solucitudAsesoramiento;
	}

	public void setSolucitudAsesoramiento(SolucitudAsesoramiento solucitudAsesoramiento) {
		this.solucitudAsesoramiento = solucitudAsesoramiento;
	}

	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	public Byte getEstado() {
		return this.estado;
	}

	public void setEstado(Byte estado) {
		this.estado = estado;
	}

	public Set getSolicitudPlanTesises() {
		return this.solicitudPlanTesises;
	}

	public void setSolicitudPlanTesises(Set solicitudPlanTesises) {
		this.solicitudPlanTesises = solicitudPlanTesises;
	}

}
