package pe.edu.unsch.entities;
// Generated 08/07/2019 08:40:20 PM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SolicitudPlanTesis generated by hbm2java
 */
@Entity
@Table(name = "solicitud_plan_tesis", catalog = "titulaciondb")
public class SolicitudPlanTesis implements java.io.Serializable {

	private int idsolicitudPlanTesis;
	private SolicitudAprobacion solicitudAprobacion;
	private String urlPlanTesis;
	private String pagoTramite;
	private String detalle;
	private String estado;
	private Set<Comision> comisions = new HashSet<Comision>(0);

	public SolicitudPlanTesis() {
	}

	public SolicitudPlanTesis(int idsolicitudPlanTesis, SolicitudAprobacion solicitudAprobacion) {
		this.idsolicitudPlanTesis = idsolicitudPlanTesis;
		this.solicitudAprobacion = solicitudAprobacion;
	}

	public SolicitudPlanTesis(int idsolicitudPlanTesis, SolicitudAprobacion solicitudAprobacion, String urlPlanTesis,
			String pagoTramite, String detalle, String estado, Set<Comision> comisions) {
		this.idsolicitudPlanTesis = idsolicitudPlanTesis;
		this.solicitudAprobacion = solicitudAprobacion;
		this.urlPlanTesis = urlPlanTesis;
		this.pagoTramite = pagoTramite;
		this.detalle = detalle;
		this.estado = estado;
		this.comisions = comisions;
	}

	@Id

	@Column(name = "idsolicitud_plan_tesis", unique = true, nullable = false)
	public int getIdsolicitudPlanTesis() {
		return this.idsolicitudPlanTesis;
	}

	public void setIdsolicitudPlanTesis(int idsolicitudPlanTesis) {
		this.idsolicitudPlanTesis = idsolicitudPlanTesis;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idsolicitud_aprobacion", nullable = false)
	public SolicitudAprobacion getSolicitudAprobacion() {
		return this.solicitudAprobacion;
	}

	public void setSolicitudAprobacion(SolicitudAprobacion solicitudAprobacion) {
		this.solicitudAprobacion = solicitudAprobacion;
	}

	@Column(name = "url_plan_tesis", length = 100)
	public String getUrlPlanTesis() {
		return this.urlPlanTesis;
	}

	public void setUrlPlanTesis(String urlPlanTesis) {
		this.urlPlanTesis = urlPlanTesis;
	}

	@Column(name = "pago_tramite", length = 45)
	public String getPagoTramite() {
		return this.pagoTramite;
	}

	public void setPagoTramite(String pagoTramite) {
		this.pagoTramite = pagoTramite;
	}

	@Column(name = "detalle", length = 100)
	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	@Column(name = "estado", length = 45)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitudPlanTesis")
	public Set<Comision> getComisions() {
		return this.comisions;
	}

	public void setComisions(Set<Comision> comisions) {
		this.comisions = comisions;
	}

}
