package pe.edu.unsch.entities;
// Generated 20/07/2019 08:17:53 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * SolicitudSustentacion generated by hbm2java
 */
public class SolicitudSustentacion implements java.io.Serializable {

	private Integer idsolicitudSustentacion;
	private SolicitudBorradora solicitudBorradora;
	private Date solicitudSustentacioncol;
	private String fecha;
	private String lugar;

	public SolicitudSustentacion() {
	}

	public SolicitudSustentacion(SolicitudBorradora solicitudBorradora) {
		this.solicitudBorradora = solicitudBorradora;
	}

	public SolicitudSustentacion(SolicitudBorradora solicitudBorradora, Date solicitudSustentacioncol, String fecha,
			String lugar) {
		this.solicitudBorradora = solicitudBorradora;
		this.solicitudSustentacioncol = solicitudSustentacioncol;
		this.fecha = fecha;
		this.lugar = lugar;
	}

	public Integer getIdsolicitudSustentacion() {
		return this.idsolicitudSustentacion;
	}

	public void setIdsolicitudSustentacion(Integer idsolicitudSustentacion) {
		this.idsolicitudSustentacion = idsolicitudSustentacion;
	}

	public SolicitudBorradora getSolicitudBorradora() {
		return this.solicitudBorradora;
	}

	public void setSolicitudBorradora(SolicitudBorradora solicitudBorradora) {
		this.solicitudBorradora = solicitudBorradora;
	}

	public Date getSolicitudSustentacioncol() {
		return this.solicitudSustentacioncol;
	}

	public void setSolicitudSustentacioncol(Date solicitudSustentacioncol) {
		this.solicitudSustentacioncol = solicitudSustentacioncol;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public String getLugar() {
		return this.lugar;
	}

	public void setLugar(String lugar) {
		this.lugar = lugar;
	}

}
