package pe.edu.unsch.entities;
// Generated 21/07/2019 10:20:59 AM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Solicitud generated by hbm2java
 */
@Entity
@Table(name = "solicitud", catalog = "titulaciondb")
public class Solicitud implements java.io.Serializable {

	private Integer idsolicitud;
	private String nombre;
	private Set<SolicitudAprobacion> solicitudAprobacions = new HashSet<SolicitudAprobacion>(0);
	private Set<SolucitudAsesoramiento> solucitudAsesoramientos = new HashSet<SolucitudAsesoramiento>(0);

	public Solicitud() {
	}

	public Solicitud(String nombre, Set<SolicitudAprobacion> solicitudAprobacions,
			Set<SolucitudAsesoramiento> solucitudAsesoramientos) {
		this.nombre = nombre;
		this.solicitudAprobacions = solicitudAprobacions;
		this.solucitudAsesoramientos = solucitudAsesoramientos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idsolicitud", unique = true, nullable = false)
	public Integer getIdsolicitud() {
		return this.idsolicitud;
	}

	public void setIdsolicitud(Integer idsolicitud) {
		this.idsolicitud = idsolicitud;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitud")
	public Set<SolicitudAprobacion> getSolicitudAprobacions() {
		return this.solicitudAprobacions;
	}

	public void setSolicitudAprobacions(Set<SolicitudAprobacion> solicitudAprobacions) {
		this.solicitudAprobacions = solicitudAprobacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "solicitud")
	public Set<SolucitudAsesoramiento> getSolucitudAsesoramientos() {
		return this.solucitudAsesoramientos;
	}

	public void setSolucitudAsesoramientos(Set<SolucitudAsesoramiento> solucitudAsesoramientos) {
		this.solucitudAsesoramientos = solucitudAsesoramientos;
	}

}
