package pe.edu.unsch.entities;
// Generated 20/07/2019 08:17:53 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * SolucitudAsesoramiento generated by hbm2java
 */
public class SolucitudAsesoramiento implements java.io.Serializable {

	private Integer idsolucitudAsesoramiento;
	private Bachiller bachiller;
	private Docente docente;
	private Solicitud solicitud;
	private String detalle;
	private String estado;
	private Set solicitudAprobacions = new HashSet(0);

	public SolucitudAsesoramiento() {
	}

	public SolucitudAsesoramiento(Bachiller bachiller, Docente docente, Solicitud solicitud) {
		this.bachiller = bachiller;
		this.docente = docente;
		this.solicitud = solicitud;
	}

	public SolucitudAsesoramiento(Bachiller bachiller, Docente docente, Solicitud solicitud, String detalle,
			String estado, Set solicitudAprobacions) {
		this.bachiller = bachiller;
		this.docente = docente;
		this.solicitud = solicitud;
		this.detalle = detalle;
		this.estado = estado;
		this.solicitudAprobacions = solicitudAprobacions;
	}

	public Integer getIdsolucitudAsesoramiento() {
		return this.idsolucitudAsesoramiento;
	}

	public void setIdsolucitudAsesoramiento(Integer idsolucitudAsesoramiento) {
		this.idsolucitudAsesoramiento = idsolucitudAsesoramiento;
	}

	public Bachiller getBachiller() {
		return this.bachiller;
	}

	public void setBachiller(Bachiller bachiller) {
		this.bachiller = bachiller;
	}

	public Docente getDocente() {
		return this.docente;
	}

	public void setDocente(Docente docente) {
		this.docente = docente;
	}

	public Solicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(Solicitud solicitud) {
		this.solicitud = solicitud;
	}

	public String getDetalle() {
		return this.detalle;
	}

	public void setDetalle(String detalle) {
		this.detalle = detalle;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public Set getSolicitudAprobacions() {
		return this.solicitudAprobacions;
	}

	public void setSolicitudAprobacions(Set solicitudAprobacions) {
		this.solicitudAprobacions = solicitudAprobacions;
	}

}
