package pe.edu.unsch.entities;
// Generated 08/07/2019 12:10:03 AM by Hibernate Tools 5.1.7.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UsuarioPerfil generated by hbm2java
 */
@Entity
@Table(name = "usuario_perfil", catalog = "titulaciondb")
public class UsuarioPerfil implements java.io.Serializable {

	private Integer idusuarioPerfil;
	private Perfil perfil;
	private Usuario usuario;
	private Byte estado;
	private Set<Docente> docentes = new HashSet<Docente>(0);
	private Set<Bachiller> bachillers = new HashSet<Bachiller>(0);
	private Set<Decano> decanos = new HashSet<Decano>(0);

	public UsuarioPerfil() {
	}

	public UsuarioPerfil(Perfil perfil, Usuario usuario) {
		this.perfil = perfil;
		this.usuario = usuario;
	}

	public UsuarioPerfil(Perfil perfil, Usuario usuario, Byte estado, Set<Docente> docentes, Set<Bachiller> bachillers,
			Set<Decano> decanos) {
		this.perfil = perfil;
		this.usuario = usuario;
		this.estado = estado;
		this.docentes = docentes;
		this.bachillers = bachillers;
		this.decanos = decanos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idusuario_perfil", unique = true, nullable = false)
	public Integer getIdusuarioPerfil() {
		return this.idusuarioPerfil;
	}

	public void setIdusuarioPerfil(Integer idusuarioPerfil) {
		this.idusuarioPerfil = idusuarioPerfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idperfil", nullable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idusuario", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "estado")
	public Byte getEstado() {
		return this.estado;
	}

	public void setEstado(Byte estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarioPerfil")
	public Set<Docente> getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Set<Docente> docentes) {
		this.docentes = docentes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarioPerfil")
	public Set<Bachiller> getBachillers() {
		return this.bachillers;
	}

	public void setBachillers(Set<Bachiller> bachillers) {
		this.bachillers = bachillers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuarioPerfil")
	public Set<Decano> getDecanos() {
		return this.decanos;
	}

	public void setDecanos(Set<Decano> decanos) {
		this.decanos = decanos;
	}

}
